### ISSUE TITLE
Issue with Limit

### ISSUE THREAD

**Issue by epinault** [joshuataylor/snowflake_elixir_ecto#2]
I am using your lastest version and latest Ecto

running this kind of query breaks

```
      limit = 10 
      Admintools.SnowflakeRepo.all(
          from(o in Admintools.Tenants.SnowflakeOrg,
            where: ilike(o.name, ^"%git%"),
            limit: ^limit
          )
        )
```

but this works
```
      Admintools.SnowflakeRepo.all(
          from(o in Admintools.Tenants.SnowflakeOrg,
            where: ilike(o.name, ^"%git%"),
            limit: 10
          )
        )
```

seems like the replacement is not handled correctly for dynamic limit in this case while that seems to work for the ilike portion

Both queries works fine with Postgres. And looking at the code, since you are doing the handling for the ecto driver, seems like something is not handling replacement? Not sure to fix it yet since I have no knowledge yet of Ecto underlying expression parsing and replacement

```
(SnowflakeEx.Error) got %SnowflakeEx.Result{columns: nil, messages: [%{error_code: "002010", message: "SQL compilation error:\nInvalid row count '?' in limit clause", severity: :error, sql_error: "2201W"}], metadata: [], num_rows: 0, rows: nil, statement: nil} while retrieving Exception.message/1 for %SnowflakeEx.Error{connection_id: nil, message: %SnowflakeEx.Result{columns: nil, messages: [%{error_code: "002010", message: "SQL compilation error:\nInvalid row count '?' in limit clause", severity: :error, sql_error: "2201W"}], metadata: [], num_rows: 0, rows: nil, statement: nil}, query: nil, snowflake: nil} (expected a string)
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:751: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.5.3) lib/ecto/adapters/sql.ex:684: Ecto.Adapters.SQL.execute/5
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:229: Ecto.Repo.Queryable.execute/4
    (ecto 3.5.4) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
```

**Comment by joshuataylor** [comment]
That's super weird, and obviously not right -- I'll add a test to ensure this is covered.

Thanks for finding this!

**Comment by epinault** [comment]
awesome! thanks! I think it s because of the :^ that is not mapped or not handle and required for Ecto Query. I have a work around meanwhile to handle the limit for my needs

**Comment by epinault** [comment]
closing as it has been 2 years and don t need it.
